Pyupgrade to 3.9
pinterest/pymemcache pull request #620
Opened 2024-11-26 04:41 UTC by daveisfera

Minimum version of 3.9
Add up to 3.13
Build improvements

2025-01-27 15:33 UTC, ikoruk commented
Hi @jparise is there any chance of getting this PR reviewed and pushed upstream? It would be nice to use a pymemcache that officially supports the newer Pythons.

2025-02-02 00:45 UTC, jparise commented
> Hi @jparise is there any chance of getting this PR reviewed and pushed upstream? It would be nice to use a pymemcache that officially supports the newer Pythons.

I no longer work at Pinterest or use pymemcache on a regular basis, but I'll try to block out some time soon to help work through the backlog of open pull requests.

2025-02-02 00:47 UTC, jparise approved these changes

2025-02-02 01:32 UTC, daveisfera commented
> I no longer work at Pinterest or use pymemcache on a regular basis, but I'll try to block out some time soon to help work through the backlog of open pull requests.

Thanks! This should be a really low risk change so hopefully should be an easy one to click merge on

2025-02-02 02:29 UTC, jparise commented
> > I no longer work at Pinterest or use pymemcache on a regular basis, but I'll try to block out some time soon to help work through the backlog of open pull requests.
> 
> 
> 
> Thanks! This should be a really low risk change so hopefully should be an easy one to click merge on

I'm afraid I no longer have that level of access (and I'm also not a `CODEREVIEWER`).

2025-02-02 08:59 UTC, cclauss requested changes

2025-02-02 08:59 UTC, cclauss commented on pyproject.toml
> +target-version = ['py39', 'py310', 'py311', 'py312', 'p313']
```suggestion
target-version = ['py39', 'py310', 'py311', 'py312', 'py313']
```

2025-02-02 08:59 UTC, cclauss commented on .github/workflows/ci.yml
> +        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', 'pypy-3.9']
```suggestion
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', 'pypy-3.10']
```
https://pypy.org/download.html

2025-02-02 08:59 UTC, cclauss commented on pyproject.toml
> +python_version = 3.13
Should this be the lowest-supported Python or the highest-supported Python?
```suggestion
python_version = 3.9
```

2025-02-02 08:59 UTC, cclauss commented on tox.ini
> +    pypy-3.13: pypy3
There is no pypy-3.13...  https://pypy.org/download.html
```suggestion
    pypy-3.10: pypy3
```

2025-02-02 08:59 UTC, cclauss commented on .github/workflows/ci.yml
> +      if: matrix.python-version == '3.13'
Please try running tox on your local machine.

This will require adding `setuptools` to `lint-requirements.txt` and dropping Python < 3.9 from `pyproject.toml`
* #608

2025-02-02 08:59 UTC, cclauss commented on .github/workflows/ci.yml
> +      if: matrix.python-version == '3.13'
This will require changes to `docs-requirements.txt` because `imghdr` was one of the dead batteries modules removed from the Standard Library in Python 3.13.
* #608

2025-02-04 07:39 UTC, cclauss approved these changes
Nice!

2025-02-05 00:28 UTC, yurushao approved these changes

2025-02-05 00:57 UTC, jparise commented on .github/workflows/ci.yml
> +      if: matrix.python-version == '3.13'
This also appears to introduce a formatting difference in `pymemcache/client/base.py`.

2025-02-05 00:59 UTC, daveisfera commented on .github/workflows/ci.yml
> +      if: matrix.python-version == '3.13'
I just pushed a commit moving that back to `3.10` to get the tests passing

2025-02-05 17:44 UTC, yurushao commented
The Lint step also failed on master branch. Probably not related to this PR.

2025-02-05 18:53 UTC, cclauss commented
>  `black --check .`
would reformat pymemcache/client/base.py

2025-02-05 18:56 UTC, daveisfera commented
> > `black --check .`
> > would reformat pymemcache/client/base.py

Pushed a commit to apply the change that `black` wanted

2025-02-05 19:55 UTC, jparise approved these changes

2025-02-05 19:56 UTC, merged